services:
  postgres:
    image: postgres
    hostname: postgres
    command: -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    restart: always
    shm_size: 256mb
    env_file: ".env"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER'" ]
      interval: 15s
      timeout: 30s
      retries: 3
    volumes:
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/initdb.d/:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8080:80"
    env_file: ".env"
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json

volumes:
  postgres_data:
    driver: local
