services:
  postgres:
    image: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    restart: always
    shm_size: 128mb
    env_file: ".env"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 15s
      timeout: 30s
      retries: 3
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8080:80"
    env_file: ".env"
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json

volumes:
  postgres_data:
    driver: local
